name: Build
permissions:
  contents: read

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ main ]

jobs:
  build-apple:
    runs-on: macos-14
    environment: Maven Central
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Rust & cargo
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.konan
            readline4k/src/rust/target
          key: rust-lib-cache-apple

      - name: Gradle Build
        run: ./gradlew build
